//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CanteenSystem.Dal
{
    using System;
    using System.Collections.Generic;
    
    public partial class Cart
    {
        public int Id { get; set; }
        public int MealMenuId { get; set; }
        public int Quantity { get; set; }
        public double Price { get; set; }
        public decimal CreatedDate { get; set; }
        public decimal UpdatedDate { get; set; }
        public System.DateTime MealAvailableDate { get; set; }
    
        public virtual MealMenu MealMenu { get; set; }
    }
}
