//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CanteenSystem.Dal
{
    using System;
    using System.Collections.Generic;
    
    public partial class MealMenuAvailability
    {
        public int Id { get; set; }
        public int MealMenuId { get; set; }
        public System.DateTime AvailabilityDate { get; set; }
    
        public virtual MealMenu MealMenu { get; set; }
    }
}
