//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CanteenSystem.Dal
{
    using System;
    using System.Collections.Generic;
    
    public partial class Payment
    {
        public long Id { get; set; }
        public string PaymentReference { get; set; }
        public System.DateTime PaymentDate { get; set; }
        public double PaymentAmount { get; set; }
        public long OrderId { get; set; }
    
        public virtual Order Order { get; set; }
    }
}
